#cloud-config
users:
  - name: ubuntu
    groups: [users, admin]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0MABxv8adiwJh4kFYhBvK2tzkp89LOVSZCG5nGgyM88UmQi/pBpoDlGztezeXnXsNqG4ytNcFeN+NhFnDSLqkrM2wgvN7/9ZoITGsemiNy9aneYDPrNAyxqyuQth1rLZ9vcUAYN+yKp2u1torf/ioK4QR02eK9geqsoJVAavVlvyqkHg84pxi/aFrsJvR0CaQvREOiZZM6tk0Pw+bdNnHU5qzoGm4ll07ziIXmY9uerJ/uTCaVV6dQ49rYiejky7dX+OVx/8E6qLmW+fgSrbxDN38uZUo22DXHKNtbQIUe/C+pB9m4eJ8TY6gxAqiSKOX6uF38dHVAteSKyc11AXL aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key-lehrperson
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget
